name: feature_style
channels:
  - pytorch
  - 1adrianb
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.5.30
  - cffi=1.14.5
  - cloudpickle=1.6.0
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=1.1.4
  - dataclasses=0.8
  - decorator=5.0.6
  - defusedxml=0.7.1
  - entrypoints=0.3
  - face_alignment=1.3.4
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf5=1.10.2
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libidn2=2.3.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.2
  - networkx=2.2
  - notebook=6.3.0
  - numba=0.53.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=3.4.1
  - openh264=2.1.0
  - openssl=1.1.1l
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.8.1
  - pywavelets=1.1.1
  - pyzmq=20.0.0
  - readline=8.1
  - scikit-image=0.17.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tbb=2020.3
  - terminado=0.9.4
  - testpath=0.4.4
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cython==0.29.23
    - dlib==19.22.1
    - idna==3.2
    - joblib==1.1.0
    - ninja==1.10.2.2
    - onnxruntime==1.7.0
    - opencv-python==4.5.1.48
    - protobuf==3.15.8
    - pytorch-msssim==0.2.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - scikit-learn==0.22
    - sklearn==0.0
    - tensorboard-logger==0.1.0
    - threadpoolctl==3.0.0
    - urllib3==1.26.7
