# Input data
resolution: 1024                 
age_min: 20                  
age_max: 70  
use_realimg: True
# Training hyperparameters                 
batch_size: 1               
epochs: 12    
iter_per_epoch: 10000
device: 'cuda'
# Optimizer parameters               
optimizer: 'ranger'
lr: 0.0001         
beta_1: 0.95                   
beta_2: 0.999
weight_decay: 0
# Learning rate scheduler                  
step_size: 10                
gamma: 0.1                                 
# Tensorboard log options
image_save_iter: 100         
log_iter: 10    
# Network setting
use_fs_encoder: True
use_fs_encoder_v2: True
fs_stride: 2
pretrained_weight_for_fs: False
enc_resolution: 256 
enc_residual: False
truncation_psi: 1
use_noise: True
randomize_noise: False      # If generator use a different random noise at each time of generating a image from z
# Loss setting
use_parsing_net: True
multi_layer_idloss: True
real_image_as_image_loss: False
feature_match_loss: False   
feature_match_loss_G: False
use_random_noise: True
optimize_on_z: False
multiscale_lpips: True
# Loss weight
w:
  l1: 0
  l2: 1
  lpips: 0.2
  id: 0.1
  landmark: 0.1
  f_recon: 0.01